// import React from 'react'
import { FcDocument } from "react-icons/fc";
import "./info.css"
const TermsAndConditions = () => {

    const termStyle={
        fontSize: "1.3rem", fontWeight: "600", color: "#2b6cb0", marginBottom: "8px",
        fontFamily:"Sansation, sans-serif",

    }


  return (
    <div className='container' >
        <h1>The Rulebook <FcDocument size={40} /></h1>
        <p>Last Updated: September 2026</p>
        <div className="content">
            <section>
          <h2 style={termStyle} >
            1. Acceptance of Terms
          </h2>
          <p>
            Welcome to <strong>Charukavya</strong>. By accessing or using our platform, you agree to comply with and be bound by these Terms and Conditions. If you do not agree, please do not use our services.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            2. User Accounts & Responsibilities
          </h2>
          <p>
            To publish articles or engage with content, you may need to create an account using email or social authentication (Google, GitHub, etc.). You are responsible for maintaining the confidentiality of your credentials and for all activities under your account.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            3. Age Eligibility & Mature Content
          </h2>
          <p>
            Users must be at least 18 years old to create an account. Creators publishing stories with mature themes, violence, or intense horror are strictly required to tag their content appropriately using the platform's content filters. Failure to tag mature content may result in immediate post removal or account suspension
          </p>
        </section>


        <section>
          <h2 style={termStyle}>
            4. Content Ownership & Copyright
          </h2>
          <p>
            Writers retain full ownership of the original content they publish on Charukavya. However, by publishing content, you grant us a non-exclusive license to display, distribute, and format your content on the platform.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            5.  Collaboration & Multi-Author Rights
          </h2>
          <p>
            When participating in 'Collab Mode,' each creator retains exclusive copyright only over the specific chapters or sections authored by them. Co-authors cannot delete, alter, or claim sole monetization rights over content generated by another user in a shared story project. Charukavya reserves the right to keep individual contributions live if one collaborator decides to delete their account.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            6. Peer-to-Peer Micro-Donations (Tipping)
          </h2>
          <p>
            Charukavya provides a gateway for readers to support creators through micro-donations (₹40 - ₹max). All transactions are processed strictly peer-to-peer via third-party UPI payment networks. Charukavya does not hold, process, or refund these funds. All tips are final, non-refundable, and sent at the reader's sole discretion. Creators are solely responsible for any applicable local taxes on earnings.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            7. Prohibited Conduct
          </h2>
          <p>Users agree not to engage in any of the following activities:</p>
          <ul style={termStyle}>
            <li>Posting plagiarized, offensive, abusive, or hate speech content.</li>
            <li>Spamming, automated bot interactions, or malicious code insertion.</li>
            <li>Attempting to breach security or disrupt backend services.</li>
          </ul>
        </section>

        <section>
          <h2 style={termStyle}>
            8. Content Removal & Termination
          </h2>
          <p>
            We reserve the right to edit, suspend, or permanently remove any content or user account that violates these terms or poses legal risks without prior notice.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            9. Limitation of Liability
          </h2>
          <p>
            Charukavya is provided "as is" without warranties of any kind. We are not liable for any direct, indirect, or incidental damages resulting from your use of the platform or loss of data.
          </p>
        </section>


        <section>
          <h2 style={termStyle}>
            10. Governing Law & Jurisdiction
          </h2>
          <p>
            These terms shall be governed by and construed in accordance with the laws of India. Any legal actions or disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts located in Bhadreswar & Chandernagar, West Bengal, India
          </p>
        </section>

        {/*  <i>patraarittik1999@gmail.com</i> */}

        <section>
          <h2 style={termStyle}>
            11. Copyright Infringement & Takedown Procedure (Indian IT Act Compliance)
          </h2>
          <p>
            <b>Charukavya</b> operates as an intermediary under Section 79 of the Information Technology Act, 2000. We do not pre-screen user-generated content, but we strictly prohibit copyright infringement. If you believe your copyrighted work has been uploaded without authorization, you may submit a formal Takedown Notice in compliance with the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules.Please send your grievance, along with proof of original ownership and the infringing URL, to our designated Grievance Email: <i>patraarittik1999@gmail.com</i>. Valid complaints will be processed and the content will be disabled expeditiously within the legally stipulated timelines.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            12. Indemnification
          </h2>
          <p>
            You agree to indemnify, defend, and hold harmless Charukavya, its creators, operators, and affiliates from and against any and all claims, liabilities, damages, losses, costs, or expenses arising out of or in any way connected with your content submissions, your use of the platform, or your violation of any third-party rights.
          </p>
        </section>

        <section>
          <h2 style={termStyle}>
            13. Changes to Terms
          </h2>
          <p>
            We reserve the right to update these terms at any time. Continued use of the platform following any modifications constitutes acceptance of the new terms.
          </p>
        </section>




        </div>
    </div>
  )
}

export default TermsAndConditions